const { VERSE_ILLUSTRATION_PROMPT } = require('./verse');
const {
  STORY_ILLUSTRATION_PROMPT,
  CONCEPT_ILLUSTRATION_PROMPT,
  CHARACTER_ILLUSTRATION_PROMPT,
  HISTORICAL_ILLUSTRATION_PROMPT,
  YOUTH_ILLUSTRATION_PROMPT,
  QA_PROMPT
} = require('./templates');

module.exports = {
  VERSE_ILLUSTRATION_PROMPT,
  STORY_ILLUSTRATION_PROMPT,
  CONCEPT_ILLUSTRATION_PROMPT,
  CHARACTER_ILLUSTRATION_PROMPT,
  HISTORICAL_ILLUSTRATION_PROMPT,
  YOUTH_ILLUSTRATION_PROMPT,
  QA_PROMPT
};
